### ISSUE TITLE
Aligned version of the MT_translated Alpaca

### ISSUE THREAD

**Issue by zhangliang-04** [lranaldii/CrossAlpaca#1]
Dear authors,
Thanks very much for the open sourcing! It seems that the order of MT_translated Alpaca data is not aligned with the English data. Would you mind providing the aligned version? Thanks a lot :)

**Comment by lranaldii** [comment]
Hi,
Thank you for your issue.
We have updated all versions, they should now be aligned with the open resources available on huggingface.
